baseURL: https://blindcomputing.org/
languageCode: en-gb
title: Blind Computing
copyright: Copyright © 2020 the Blind Computing Team. This project is licensed under the GNU AGPL, version 3.0 or later.
disqusShortname: blind-computing

enableRobotsTXT: True

outputs:
  home:
  - HTML
  - RSS
  - AMP
  page:
  - HTML
  - AMP

imaging:
  bgColor: #ffffff
