baseURL: https://blindcomputing.org/
languageCode: en-gb
title: Blind Computing
disqusShortname: blind-computing

outputs:
  home:
  - HTML
  - Sitemap
  - RSS
  - AMP
  page:
  - HTML
  - AMP

imaging:
  bgColor: #ffffff
